name: 'action'
description: 'Run Robot Framework tests'
inputs:
  canvos_tag:
    description: 'CanvOS Tag'
    required: true
  custom_image_tag:
    description: 'Custom Image Tag'
    required: true
  image_registry:
    description: 'Image Registry'
  os_distribution:
    description: 'OS Distribution'
    required: true
  k8s_distribution:
    description: 'K8S Distribution'
    required: true
  arch:
    description: 'Architecture'
    required: true
  base_image:
    description: 'Base Image'
  build_type:
    description: 'Build Type'
    required: true
  output_artifact:
    description: 'Output Artifact Type'
    required: true
  upload_iso_to_s3:
    description: 'Upload ISO to S3'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: ./.github/actions/canvos/canvos-build.sh
      env:
        canvos_tag: ${{ inputs.canvos_tag }}
        custom_image_tag: ${{ inputs.custom_image_tag }}
        image_registry: ${{ inputs.image_registry }}
        os_distribution: ${{ inputs.os_distribution }}
        k8s_distribution: ${{ inputs.k8s_distribution }}
        arch: ${{ inputs.arch }}
        base_image: ${{ inputs.base_image }}
        build_type: ${{ inputs.build_type }}
        output_artifact: ${{ inputs.output_artifact }}
        GCP_SPECTRO_DEV_PUBLIC_BASE64_ENCODED_JSON: ${{ inputs.GCP_SPECTRO_DEV_PUBLIC_BASE64_ENCODED_JSON }}
        GOVC_URL: ${{ inputs.GOVC_URL }}
        GOVC_INSECURE: ${{ inputs.GOVC_INSECURE }}
        GOVC_USERNAME: ${{ inputs.GOVC_USERNAME }}
        GOVC_PASSWORD: ${{ inputs.GOVC_PASSWORD }}
        GOVC_FOLDER: ${{ inputs.GOVC_FOLDER }}
        GOVC_DATACENTER: ${{ inputs.GOVC_DATACENTER }}
        GOVC_DATASTORE: ${{ inputs.GOVC_DATASTORE }}
        GOVC_NETWORK: ${{ inputs.GOVC_NETWORK }}
        GOVC_HOST: ${{ inputs.GOVC_HOST }}
        GOVC_CLUSTER: ${{ inputs.GOVC_CLUSTER }}
        upload_iso_to_s3: ${{ inputs.upload_iso_to_s3 }}
    - shell: bash
      run: ./.github/actions/canvos/canvos-clean.sh
    - shell: bash
      run: sudo rm -rf ${{ github.workspace }}/*
      


