name: 'action'
description: 'Run Robot Framework tests'
inputs:
  canvos_tag:
    description: 'CanvOS Tag'
    required: true
  custom_image_tag:
    description: 'Custom Image Tag'
    required: true
  image_registry:
    description: 'Image Registry'
  image_repo:
    description: 'Image Repo'
    required: true
  os_distribution:
    description: 'OS Distribution'
    required: true
  k8s_distribution:
    description: 'K8S Distribution'
    required: true
  iso_name:
    description: 'ISO Name'
    required: true
  arch:
    description: 'Architecture'
    required: true
  base_image:
    description: 'Base Image'
  build_type:
    description: 'Build Type'
    required: true
  output_artifact:
    description: 'Output Artifact Type'
    required: true
  upload_iso_to_s3:
    description: 'Upload ISO to S3'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: ./.github/actions/canvos/canvos-build.sh
      env:
        canvos_tag: ${{ inputs.canvos_tag }}
        custom_image_tag: ${{ inputs.custom_image_tag }}
        image_registry: ${{ inputs.image_registry }}
        image_repo: ${{ inputs.image_repo }}
        os_distribution: ${{ inputs.os_distribution }}
        k8s_distribution: ${{ inputs.k8s_distribution }}
        iso_name: ${{ inputs.iso_name }}
        arch: ${{ inputs.arch }}
        base_image: ${{ inputs.base_image }}
        build_type: ${{ inputs.build_type }}
        output_artifact: ${{ inputs.output_artifact }}
        upload_iso_to_s3: ${{ inputs.upload_iso_to_s3 }}
        GCP_SPECTRO_DEV_PUBLIC_BASE64_ENCODED_JSON: ${{ secrets.GCP_SPECTRO_DEV_PUBLIC_BASE64_ENCODED_JSON }}
        VSPHERE_URL: ${{ secrets.VSPHERE_URL }}
        VSPHERE_USERNAME: ${{ secrets.VSPHERE_USERNAME }}
        VSPHERE_PASSWORD: ${{ secrets.VSPHERE_PASSWORD }}
        VSPHERE_FOLDER: ${{ secrets.VSPHERE_FOLDER }}
        VSPHERE_DATACENTER: ${{ secrets.VSPHERE_DATACENTER }}
        VSPHERE_DATASTORE: ${{ secrets.VSPHERE_DATASTORE }}
        VSPHERE_NETWORK: ${{ secrets.VSPHERE_NETWORK }}
        VSPHERE_HOST: ${{ secrets.VSPHERE_HOST }}
        VSPHERE_CLUSTER: ${{ secrets.VSPHERE_CLUSTER }}


